### ISSUE TITLE
transparent navigationBar issue

### ISSUE THREAD

**Issue by almaz010891** [KeepSafe/TapTargetView#233] opened 2017-11-29 15:38 UTC
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

Hi! Thanks for library!
When I used this with transparent navigationBar, target don't draw view until transpaernt navigationBar
See screenshot
![device-2017-11-29-173457](https://user-images.githubusercontent.com/4091750/33383449-fd8db5ac-d52b-11e7-922f-3b3a55bbd885.png)

**Comment by linkinheroes** [comment] 2018-01-01 21:17
The same problem with status bar - it changes color to grey.

**Comment by Dgilliams** [comment] 2018-06-12 15:28
Hey there! I'm seeing this same issue on a Samsung S8. Was there a fix for this? Any sort of workaround?

**Comment by Dgilliams** [comment] 2018-06-19 13:09
@KeepSafeAccount @xiphirx @
I think this code below may be the cause of the issue. Has anyone tried using getWindowDisplayFrame? or attaching to the window decor instead?

from line 452 in taptargetview:
              final Rect rect = new Rect();
              boundingParent.getWindowVisibleDisplayFrame(rect);

              // We bound the boundaries to be within the screen's coordinates to
              // handle the case where the layout bounds do not match
              // (like when FLAG_LAYOUT_NO_LIMITS is specified)
              topBoundary = Math.max(0, rect.top);
              bottomBoundary = Math.min(rect.bottom, displayMetrics.heightPixels);

**Comment by fabredthunder** [comment] 2018-06-26 18:58
Hey,

Someone find a solution ? 
Same issue on my S8+ in fullscreen (no navigationbar)

**Comment by Dgilliams** [comment] 2018-06-26 19:05
I found that if you double tap the dot on the right of the navigation bar, it will toggle the Samsung navigation bars "hide/show navigation bar" feature. With it enabled, the navigation bar will auto hide and the transparency issue happens. With it disabled the navigation bar will stay put and the layout looks as expected. :/

**Comment by fabredthunder** [comment] 2018-06-26 19:08
Yep but i think every S8 user's are in fullscreen mode so it's not good :/
Did you try to edit the code at line 452 in taptargetview like you say in your previous message ?

**Comment by AliEsaAssadi** [comment] 2018-07-02 15:28
hey guys, I will give you a temporary fix for the problem.

create an dialog instance;
```
AlertDialog dialog = new AlertDialog.Builder(this).show();
dialog.hide();
```
then pass the instance:

TapTargetSequence -> `new TapTargetSequence(dialog)`
TapTargetView -> `TapTargetView.showFor(dialog,.....);`

**Closed** 2018-07-05 02:41 UTC
Labels: bug

**Comment by mhartvick** [comment] 2018-08-07 14:01
Hey guys, I'm still having the issue with the latest release on a Samsung Note 8. The release is probably fixing transparent navigation bar, but not the Samsung "auto disappear" one. Workaround with the dialog works fine though.

Will dig deeper if I have time later to fix it
