### ISSUE TITLE
Cannot assign color white to title or description

### ISSUE THREAD

**Issue by pflammertsma** [KeepSafe/TapTargetView#129] opened 2017-02-07 03:10 UTC
- [x] I have verified the issue exists on the latest version
- [x] I am able to reproduce it

**Version used: 1.7.0**

**Stack trace: N/A**

**Android version: 6.0.1 and 4.4.0**

Due to TapTargetView's internal representation of `-1` as `UNSET_COLOR`, specifying `0xffffffff` (e.g. from a color resource or as `Color.WHITE`) will be overridden to black if TapTargetView establishes that the app is using a dark theme.

See: TapTargetView:553, 560 and 567.

**Comment by xiphirx** [comment] 2017-02-07 03:11
Dupe of #123. Fixed in next version

**Closed by xiphirx** 2017-02-07 03:11 UTC
