### ISSUE TITLE
TapTarget on recycler view item not working

### ISSUE THREAD

**Issue by benzabill** [KeepSafe/TapTargetView#141] opened 2017-03-01 20:03 UTC
- [ Yes] I have verified the issue exists on the latest version
- [ Yes] I am able to reproduce it

**Version used:** 1.8

Does tap target work on recycler view item? The stacktrace (if you click into the code) shows that the width is -230, which is less than 0. But both the width and measured width are actually 1022. 

I'm pulling the view through
`                                               View view = linearLayoutManager.findViewByPosition(position);
`
and passing it through if it's not null. I know the view is viable because I used an animation library (YoYo, an animation library on github) on this same view and it does work on it properly.

**Does recycler view do something funky here?**

**Stack trace:**
03-01 14:57:34.025 25215-25215/bentseytlin.lovetap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: bentseytlin.lovetap, PID: 25215
                                                                     java.lang.IllegalArgumentException: Layout: -230 < 0
                                                                         at android.text.Layout.<init>(Layout.java:182)
                                                                         at android.text.StaticLayout.<init>(StaticLayout.java:478)
                                                                         at android.text.StaticLayout.<init>(StaticLayout.java:464)
                                                                         at android.text.StaticLayout.<init>(StaticLayout.java:442)
                                                                         at android.text.StaticLayout.<init>(StaticLayout.java:422)
                                                                         at com.getkeepsafe.taptargetview.TapTargetView.updateTextLayouts(TapTargetView.java:824)
                                                                         at com.getkeepsafe.taptargetview.TapTargetView$9.onGlobalLayout(TapTargetView.java:427)
                                                                         at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2106)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Android version:**
7.1.1

**Comment by xiphirx** [comment] 2017-03-02 00:06
Can you share the code you're using to display the tap target? Is the view you're targeting visible?

**Comment by benzabill** [comment] 2017-03-02 16:37
The view is visible yes! I swapped a call to showTapSequence with a call to animate the same view and the animation fired as expected.

```
private void showTapSequence(View view) {

        final TapTargetSequence sequence = new TapTargetSequence(getActivity())
                .targets(
                        // Specify the target radius (in dp)
                        TapTarget.forView(view, "Words words words")
                                // All options below are optional
                                .outerCircleColor(R.color.colorPrimary)      // Specify a color for the outer circle
                                .targetCircleColor(R.color.white)   // Specify a color for the target circle
                                .titleTextSize(20)                  // Specify the size (in sp) of the title text
                                .titleTextColor(R.color.white)      // Specify the color of the title text
                                .descriptionTextSize(18)            // Specify the size (in sp) of the description text
                                .descriptionTextColor(R.color.white)  // Specify the color of the description text
                                .textColor(R.color.white)            // Specify a color for both the title and description text
                                .textTypeface(Typeface.SANS_SERIF)  // Specify a typeface for the text
                                .dimColor(R.color.black)            // If set, will dim behind the view with 30% opacity of the given color
                                .drawShadow(true)                   // Whether to draw a drop shadow or not
                                .cancelable(true)                  // Whether tapping outside the outer circle dismisses the view
                                .tintTarget(false)                   // Whether to tint the target view's color
                                .transparentTarget(true)           // Specify whether the target is transparent (displays the content underneath)
                                .targetRadius(50)
                                .id(1)
                )
                .listener(new TapTargetSequence.Listener() {
                    // This listener will tell us when interesting(tm) events happen in regards
                    // to the sequence
                    @Override
                    public void onSequenceFinish() {
                        Log.d("TapTargetView", "onSequenceFinish");
                    }

                    @Override
                    public void onSequenceStep(TapTarget lastTarget) {
                        Log.d("TapTargetView", "Clicked on " + lastTarget.id());
                    }

                    @Override
                    public void onSequenceCanceled(TapTarget lastTarget) {
                    }
                });
        sequence.considerOuterCircleCanceled(true);
        sequence.continueOnCancel(true);
        sequence.start();
    }
```

**Comment by xiphirx** [comment] 2017-03-02 23:07
I'm not sure why using a `TapTargetSequence` would be any different from a regular `TapTargetView` since a `TapTargetSequence` just creates a `TapTargetView` internally... Do you have a minimum layout + activity that exhibits this problem?

**Comment by benzabill** [comment] 2017-03-02 23:19
I am using a TapTargetSequence because of the 3 final calls to make it so that clicking anywhere on the screen will get rid of the target things. I am using it as a loose visual guide rather than a strict sequence.

No, but I was wondering if others had used it in a recycler view before

**Comment by xiphirx** [comment] 2017-03-02 23:25
Others have used it in a `RecyclerView` before, myself included. It would be great if you can share a layout + code to cause the issue to reproduce

The exception you're getting tends to come from attempting to fit a `StaticLayout` in a very small space (such as an invisible view). I've only seen it once before in #74 and I haven't been able to directly reproduce it.

**Comment by xiphirx** [comment] 2017-03-13 18:21
Closing due to lack of information. Please comment when you can provide a layout that causes this issue. I'm unable to reproduce this on my own :(

**Closed by xiphirx** 2017-03-13 18:21 UTC
Labels: needs info

**Comment by avtarsingh1122** [comment] 2017-03-14 07:03
the tap target view is not running inside fragments . in devices with api level 23 vr 6.0.1 
showing the above issues 
java.lang.IllegalArgumentException: Layout: -230 < 0
