### ISSUE TITLE
"java.lang.IllegalArgumentException: Given null view to target" when calling TapTarget.forToolbarMenuItem

### ISSUE THREAD

**Issue by henrichg** [KeepSafe/TapTargetView#168] opened 2017-05-08 08:27 UTC
- [ ] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**
Latest: 1.9.1

**Stack trace:**
Fatal Exception: java.lang.IllegalArgumentException: Given null view to target
       at com.getkeepsafe.taptargetview.ViewTapTarget.<init>(ViewTapTarget.java:31)
       at com.getkeepsafe.taptargetview.ToolbarTapTarget.<init>(ToolbarTapTarget.java:36)
       at com.getkeepsafe.taptargetview.TapTarget.forToolbarMenuItem(TapTarget.java:151)
       at sk.henrichg.phoneprofilesplus.EditorProfilesActivity.showTargetHelps(EditorProfilesActivity.java:1956)
       at sk.henrichg.phoneprofilesplus.EditorProfilesActivity.access$500(EditorProfilesActivity.java:67)
       at sk.henrichg.phoneprofilesplus.EditorProfilesActivity$6.run(EditorProfilesActivity.java:513)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Android version:**
Reported FC - API level <= 19

My application uses android.support.v7.widget.Toolbar, support lib version: 25.3.1, toolbar is act as the ActionBar via setSupportActionBar().

**Comment by tijee** [comment] 2017-05-29 08:20
+1

**Comment by babramovitch** [comment] 2017-05-29 09:13
I think I figured this one out.

The sample app is inflating the toolbar with the menu.

```
final Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
toolbar.inflateMenu(R.menu.menu_main);
```
I was using setSupportActionBar(toolbar) and then inflating the menu in onCreateOptionsMenu

`getMenuInflater().inflate(R.menu.menu_main, menu);`

So when you're calling  

`TapTarget.forToolbarMenuItem(toolbar, R.id.item_id, "test")`

The toolbar doesn't actually have any menu items and throws the error.

I'm not sure if inflating the menu in the toolbar, and then calling setSupportActionBar(toolbar) will cause unknown problems though?

This should really be clarified in the documentation if there's no problem inflating the toolbar in addition to the setSupportActionBar(toolbar) OR make it work with the support method.

**Comment by tijee** [comment] 2017-05-29 09:30
Thanks for your help @babramovitch, unfortunately `toolbar.inflateMenu()` can't seem to work well with `setSupportActionBar`, `onPrepareOptionsMenu` is not called. I'll try to work around with the item bounds.

**Comment by babramovitch** [comment] 2017-05-29 09:52
@tijee Weird, it does call `onPrepareOptionsMenu `when I do it, and the actions all appear to work.  I just haven't had enough time yet to look for other side effects.   It might be worth taking another look at that before moving to the bounds?

This was on a LG G4 running 6.0.1 and a Moto G running 4.4

**Comment by tijee** [comment] 2017-05-29 09:54
Yeah I'm not sure maybe I need to look further, for now what I'm doing is creating my menu as usual in `onCreateOptionsMenu()` with `getMenuInflater()`, plus inflate the menu in the toolbar itself. I'm not sure what it does under the hood but it works :)

**Comment by fgagneten** [comment] 2017-06-12 14:23
Any solution about this issue? I get: 
   
    Caused by: java.lang.IllegalArgumentException: Given null view to target

**Comment by babramovitch** [comment] 2017-06-12 19:56
@fgagneten The method I described above is still working for me and I haven't encountered any problems so far, although to be cautious, I only load the menu into the toolbar if I'm going to show a tap target.  I'd give it a shot. I think that's the best you're going to get pending the app being updated to work with the support actionbar alone.

**Comment by EliuTimana** [comment] 2017-06-13 05:59
@fgagneten check this out https://github.com/KeepSafe/TapTargetView/issues/168#issuecomment-304613778

**Comment by fgagneten** [comment] 2017-06-26 13:07
Change:

    getMenuInflater().inflate(R.menu.main, menu);

With the following line:

    toolbar.inflateMenu(R.menu.main);

**Comment by henrichg** [comment] 2017-06-29 16:49
@fgagneten working good. No more reported FC in Crashlitics. Thank you.

**Comment by xiphirx** [comment] 2017-07-16 08:37
This is interesting. Is there a sample project that reproduces this issue?

**Comment by babramovitch** [comment] 2017-07-16 15:38
@xiphirx  In theory all you need to do is take the sample app, and remove the line 

https://github.com/KeepSafe/TapTargetView/blob/master/app/src/main/java/com/getkeepsafe/taptargetviewsample/MainActivity.java

toolbar.inflateMenu(R.menu.menu_main);

**Comment by babramovitch** [comment] 2017-07-16 15:44
@xiphirx  I can put one together quickly later.  It's just taking the sample app and removing line 31, and also configuring the the toolbar via setSupportActionBar

**Comment by xiphirx** [comment] 2017-07-17 01:38
So the issue here is that by setting up the `Toolbar` to act as an `ActionBar`, you're also making the menu inflation not immediately deterministic. 

In my testing, `onCreateOptionsMenu` or `onPrepareOptionsMenu` are called after `onResume` and after `onPostResume`, so there's no lifecycle method to rely on to be sure that the menu has been inflated and attached to the view hierarchy.

What you can do, though, is listen for the next immediate layout of the `Toolbar` after inflating the menu in `onCreateOptionsMenu` or `onPrepareOptionsMenu`.  Here's some sample code to do just that:
```
static void onNextLayout(final View view, final Runnable runnable) {
    final ViewTreeObserver observer = view.getViewTreeObserver();
    observer.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
      @Override
      public void onGlobalLayout() {
        final ViewTreeObserver trueObserver;

        if (observer.isAlive()) {
          trueObserver = observer;
        } else {
          trueObserver = view.getViewTreeObserver();
        }

        removeOnGlobalLayoutListener(trueObserver, this);

        runnable.run();
      }
    });
  }

  static void removeOnGlobalLayoutListener(ViewTreeObserver observer,
                                           ViewTreeObserver.OnGlobalLayoutListener listener) {
    if (Build.VERSION.SDK_INT >= 16) {
      observer.removeOnGlobalLayoutListener(listener);
    } else {
      observer.removeGlobalOnLayoutListener(listener);
    }
  }

  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_main, menu);
    onNextLayout(toolbar, new Runnable() {
      @Override
      public void run() {
        showTapTargetView();
      }
    });

    return true;
  }
```

This isn't something that the library can feasibly do well for you, so I'd advise moving away from "setSupportActionBar" entirely and just using the `Toolbar` directly.

**Closed by xiphirx** 2017-07-17 01:38 UTC
Labels: needs info

**Comment by filipebezerra** [comment] 2017-10-23 15:21
This is my solution:

Firtly we must follow the [activity lifecycle](https://github.com/xxv/android-lifecycle), so to configure the tap targets I used the `onPrepareOptionsMenu()` callback, example:

```
@Override public boolean onPrepareOptionsMenu(Menu menu) {
    menu.findItem(R.id.action_map).setVisible(presenter.canOpenMap());
    initializeDiscovery();
    return super.onPrepareOptionsMenu(menu);
}
```

Then we must to wait the `ActionMenuView` to laid out, first let's find this view:

```
final Toolbar toolbar = findViewById(R.id.toolbar);

View toolbarChild;
ActionMenuView actionMenuView = null;
for (int i = 0; i < toolbar.getChildCount(); i++) {
    toolbarChild = toolbar.getChildAt(i);

    if (toolbarChild instanceof ActionMenuView) {
        actionMenuView = (ActionMenuView) toolbarChild;
        break;
    }
}
```

And now we must to `addOnGlobalLayoutListener`:

```
if (actionMenuView != null) {
    ViewUtils.onLaidOut(actionMenuView, () -> {
        List<TapTarget> targets = new ArrayList<>();
        targets.add(forView(findViewById(R.id.fab), "Fab", "Nice"));

        if (presenter.canOpenMap()) {
            targets.add(forToolbarMenuItem(toolbar, R.id.action_map, "Map", "Great"));
        }

        targets.add(forToolbarMenuItem(toolbar, R.id.action_share, "Share", "Cool"));

        displayDiscovery(targets);
    });
}
```

My [`ViewUtils` class](https://gist.github.com/filipebezerra/71c84cafa0b1b95d63b7fc3ec75483d3)

**Comment by eskalera** [comment] 2017-11-09 11:36
I am trying to do the same but for a menu item inside the overflow menu.
```
<item
        android:id="@+id/sign_out_menu"
        android:title="@string/sign_out"
        app:showAsAction="never"/>
```
Trying to target this menu item always returns the 
> Fatal Exception: java.lang.IllegalArgumentException: Given null view to target

I am starting to think this has something to do with the fact that `showAsAction="never"` is set and therefore actionview is always null.

Has the library consider this usecase?

**Comment by toukea** [comment] 2018-11-30 21:39
> Any solution about this issue? I get:
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Given null view to target
> ```

I have just use a mHandler.postDelay(runnable, 500) to display tap target. a this time all view was created and ItemMenu inflatted.

**Comment by coskungun** [comment] 2019-10-11 08:31
> Change:
> 
> ```
> getMenuInflater().inflate(R.menu.main, menu);
> ```
> 
> With the following line:
> 
> ```
> toolbar.inflateMenu(R.menu.main);
> ```

this code with my problem solved. Thanks

**Comment by iman2420** [comment] 2023-11-13 14:43
i use this :

```
class MyActivity : AppCompatActivity(), OnMenuVisibilityListener {

    override fun onMenuVisibilityChanged(isVisible: Boolean) {
        if (isVisible) {
            // Menu is opened
            // Perform actions when the menu is opened
        } else {
            // Menu is closed
            // Perform actions when the menu is closed
        }
    }

    // Rest of your activity code

}
```
