### ISSUE TITLE
Exception: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by v-grishechko** [KeepSafe/TapTargetView#169] opened 2017-05-16 12:23 UTC
- [x] I have verified the issue exists on the latest version
- [ ] I am able to reproduce it

**Version used:**
1.9.1
**Stack trace:**
Fatal Exception: java.lang.UnsupportedOperationException
       at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:424)
       at com.getkeepsafe.taptargetview.TapTargetView.onDraw(TapTargetView.java:661)
       at android.view.View.draw(View.java:10994)
       at android.view.View.getHardwareLayer(View.java:10234)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2863)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:10997)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2126)
       at android.view.View.getDisplayList(View.java:10435)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:873)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:1910)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2445)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
**Android version:**
4.0.3 and 4.0.4 only

This crashes come from Crashlytics. I was investigated problem himself and it's old bug on some devices of different manufactures Android 4.0.3 and 4.0.4 versions.

**Comment by marbat87** [comment] 2017-05-17 07:06
Duplicate of #164 .
It has been fixed in latest snapshot yet.

Regards.

**Closed** 2017-05-17 07:27 UTC
