### ISSUE TITLE
Exception java.lang.UnsupportedOperationException :: Android API 15

### ISSUE THREAD

**Issue by ay1man4** [KeepSafe/TapTargetView#199] opened 2017-08-24 22:23 UTC
- [Yes] I have verified the issue exists on the latest version
- [No] I am able to reproduce it

**Version used:**
1.9.1
**Stack trace:**

Exception java.lang.UnsupportedOperationException:
android.view.GLES20Canvas.clipPath (GLES20Canvas.java:408)
com.getkeepsafe.taptargetview.TapTargetView.onDraw (TapTargetView.java:661)
android.view.View.draw (View.java:11030)
android.view.View.getHardwareLayer (View.java:10268)
android.view.ViewGroup.drawChild (ViewGroup.java:2874)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:2500)
android.view.View.draw (View.java:11033)
android.widget.FrameLayout.draw (FrameLayout.java:450)
com.android.internal.policy.impl.PhoneWindow$DecorView.draw (PhoneWindow.java:2274)
android.view.View.getDisplayList (View.java:10469)
android.view.HardwareRenderer$GlRenderer.draw (HardwareRenderer.java:842)
android.view.ViewRootImpl.draw (ViewRootImpl.java:1969)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1693)
android.view.ViewRootImpl.handleMessage (ViewRootImpl.java:2505)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4514)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:790)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:557)
dalvik.system.NativeStart.main (NativeStart.java)
**Android version:**
Android API 15
Android OS: 4.0.4

**Comment by xiphirx** [comment] 2017-08-25 05:57
Duplicate of #164, please use a snapshot

**Closed by xiphirx** 2017-08-25 05:57 UTC
