### ISSUE TITLE
java.lang.IllegalArgumentException: Given null view to target" when calling TapTarget.forToolbarMenuItem

### ISSUE THREAD

**Issue by peter1408** [KeepSafe/TapTargetView#184] opened 2017-07-06 10:16 UTC
Null view , when calling tapTarget view inside fragment which has a menu option 
  ```
@Override
    public void onCreate(Bundle savedInstanceState) {
....XXX .....
 this.setHasOptionsMenu(true);
}
```

```
 @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        super.onCreateOptionsMenu(menu, inflater);
       inflater.inflate(R.menu.menu_phone_description, menu);

    }
```

```
 ((PhoneDescription) getActivity()).toolbar.inflateMenu(R.menu.menu_phone_description);
        new TapTargetSequence(getActivity())
                .targets(
                       TapTarget.forToolbarMenuItem(
                                ((PhoneDescription3) getActivity()).toolbar,
                                R.id.ic_screenshot, "Spec in Pocket!", "Want to share the specs with a friend? With a single tap of the smart screenshot button get the entire snapshot of the spec-sheet.")
                                .transparentTarget(true)
                                .cancelable(false)
                                .drawShadow(true)
                                .tintTarget(false),
            

```
 **## TapTarget.forToolbarMenuItem(
                                ((PhoneDescription3) getActivity()).toolbar, (gets Crashed at this position )**

**Comment by xiphirx** [comment] 2017-07-16 08:10
Are you setting the toolbar as the action bar in your activity?

**Comment by xiphirx** [comment] 2017-07-16 08:19
Also dupe of #168

**Closed by xiphirx** 2017-07-16 08:19 UTC
Labels: needs info
