### ISSUE TITLE
java.lang.UnsupportedOperationException in com.getkeepsafe.taptargetview.TapTargetView.onDraw

### ISSUE THREAD

**Issue by olkazmin** [KeepSafe/TapTargetView#183] opened 2017-06-27 16:04 UTC
Hi

Got the following crash from crash reporting service.

Android: 4.0.4
Manufacturer: Fly
Model: IQ441

java.lang.UnsupportedOperationException
	at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:412)
	at com.getkeepsafe.taptargetview.TapTargetView.onDraw(TapTargetView.java:661)
	at android.view.View.draw(View.java:11015)
	at android.view.View.getHardwareLayer(View.java:10253)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2947)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:858)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2089)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4666)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
	at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by xiphirx** [comment] 2017-07-16 08:06
Dupe of #164

**Closed by xiphirx** 2017-07-16 08:06 UTC
