### ISSUE TITLE
The selected item is merged with the background

### ISSUE THREAD

**Issue by hazexzo** [KeepSafe/TapTargetView#110] opened 2017-01-15 19:40 UTC
Tried 1.6.0 and 1.6.1 versions. 
Once the application is started, the item in a toolbar similar to the background.
![qcgimyeucb0](https://cloud.githubusercontent.com/assets/25138137/21965552/257e0000-db6b-11e6-848b-0dffd76cbb15.jpg)

When minimize my app and re-enter, I got this 
![0czrigpyyau](https://cloud.githubusercontent.com/assets/25138137/21965554/28f04c20-db6b-11e6-8e0e-d00b60b5098e.jpg)

With elements in layout situation is vice versa. First displayed correctly, then similar to the background.

**Comment by xiphirx** [comment] 2017-01-15 21:08
Duplicate of #104 which has been fixed but not released yet

**Closed by xiphirx** 2017-01-15 21:08 UTC

**Comment by xiphirx** [comment] 2017-01-16 02:46
Please use the recently released version 1.7.0 to fix this

**Comment by hazexzo** [comment] 2017-01-19 11:54
Thanks. Now I have another problem.
My FAB and icons similar to the background. 
.setIcon doesn't help. Result still the same.
![jyc39syksei](https://cloud.githubusercontent.com/assets/25138137/22105856/c3f0c34a-de4e-11e6-9eb9-0d01300feac0.jpg)

**Comment by xiphirx** [comment] 2017-01-19 18:09
You need to use an icon that has a transparent background. Unfortunately the tint target option cannot change parts of view, but only the entire view. That's what you're seeing with the entire fab being green. I'd advise just using a transparent target for fabs

**Comment by hazexzo** [comment] 2017-01-19 21:11
Ok. 
Can you please kelp me one more time?
Before I moved this code to the separate class everything worked correctly. But now **onSequenceStep** doesn't fulfills. I need that would be after a certain step breakdowns focus on view, which is below the visible part of the layout. What could be the problem? If you do not understand, I will try to explain more clearly
```
public class ShowTutorial implements TapTargetSequence.Listener { 

private Activity activity; 
private TapTargetSequence tapTargetSequence; 
private TextView tvFlavorsTutorial; 
private LinearLayout flavorContainer; 

public ShowTutorial(Activity act) { 
this.activity = act; 
tapTargetSequence = new TapTargetSequence(activity); 
tvFlavorsTutorial = (TextView) activity.findViewById(R.id.tvFlavorsTutorial); 
flavorContainer = (LinearLayout) activity.findViewById(R.id.flavorContainer); 
} 


public void startTutorial() { 
Toolbar toolbar = (Toolbar) activity.findViewById(R.id.main_tool_bar); 
TextView a = (TextView) activity.findViewById(R.id.a); 
TextView b = (TextView) activity.findViewById(R.id.b); 
TextView c = (TextView) activity.findViewById(R.id.c); 
TextView d = (TextView) activity.findViewById(R.id.d); 
TextView e = (TextView) activity.findViewById(R.id.e); 
Button f = (Button) activity.findViewById(R.id.f); 
Button g = (Button) activity.findViewById(R.id.g); 
Button h = (Button) activity.findViewById(R.id.h); 
RadioGroup i = (RadioGroup) activity.findViewById(R.id.i); 

tapTargetSequence.targets( 
TapTarget.forToolbarNavigationIcon(toolbar, "text", "text.").id(1), 
TapTarget.forToolbarOverflow(toolbar, "text", "text.").id(2), 
TapTarget.forView(tvNicotineStrange, "text", "text.").id(3), 
TapTarget.forView(tvVgNicTutorial, "text", "text.").id(4), 
TapTarget.forView(tvPgBaseTutorial, "text", "text.").id(5), 
TapTarget.forView(tvAmountBaseTutorial, "text", "text.").id(6), 
TapTarget.forView(tvNicBaseTutorial, "text", "text.").id(7), 
TapTarget.forView(tvFlavorsTutorial, "text", "text.") .targetRadius(60).id(8), 
TapTarget.forView(flavorAmountRadioGroup, "text", "text.") .targetRadius(25).transparentTarget(true).id(9), 
TapTarget.forView(btnAddFlavor, "text", "text").id(10), 
TapTarget.forView(btnFavFlavor, "text", "text").id(11), 
TapTarget.forView(btnAddToFavFlavor, "text", "text").id(12), 
TapTarget.forView(btnFavFlavor, "text", "text").id(13) ).start(); 
} 

@Override 
public void onSequenceFinish() { 

} 

@Override 
public void onSequenceStep(TapTarget lastTarget) { 

//**Here I have a trouble.** 
if (lastTarget.id() == 5) { 
tvFlavorsTutorial.requestFocus(); 
} 
if (lastTarget.id() == 7) { 
flavorContainer.requestFocus(); 
} 
} 

@Override 
public void onSequenceCanceled(TapTarget lastTarget) { 

} 
}
```
